name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend Image
        run: docker build -t certgen-backend ./backend

      - name: Build Frontend Image
        run: docker build -t certgen-frontend ./frontend

      - name: Run Docker Compose (for testing)
        run: |
          docker-compose up -d
          sleep 10
          curl -I http://localhost:3000 || echo "Frontend not reachable"
          curl -I http://localhost:5000 || echo "Backend not reachable"
